# Generated by Django 5.2.7 on 2025-12-01 22:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_scheduleentry_options_remove_course_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код специальности')),
                ('name_kk', models.CharField(max_length=200, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-due_date'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-academic_year', 'semester', 'name'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-date'], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AlterModelOptions(
            name='scheduleentry',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Работа студента', 'verbose_name_plural': 'Работы студентов'},
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='student',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('homework', 'Домашнее задание'), ('project', 'Проект'), ('quiz', 'Контрольная работа'), ('exam', 'Экзамен'), ('lab', 'Лабораторная работа')], default='homework', max_length=50, verbose_name='Тип задания'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.IntegerField(default=100, verbose_name='Максимальный балл'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=9, verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3, verbose_name='Кредиты'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Осенний'), (2, 'Весенний')], default=1, verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='main.assignment', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='grade',
            name='letter_grade',
            field=models.CharField(blank=True, choices=[('A', 'A (отлично)'), ('B', 'B (хорошо)'), ('C', 'C (удовлетворительно)'), ('D', 'D (плохо)'), ('F', 'F (неудовлетворительно)')], max_length=5, verbose_name='Буквенная оценка'),
        ),
        migrations.AddField(
            model_name='grade',
            name='topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AddField(
            model_name='profile',
            name='iin',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИИН'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='classroom',
            field=models.CharField(blank=True, max_length=50, verbose_name='Аудитория'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='groups',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='schedule_entries', to='main.profile', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст работы'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(verbose_name='Срок сдачи'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(blank=True, max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='main.submission', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='text',
            field=models.TextField(verbose_name='Рекомендация'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='main.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.assignment', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
        migrations.CreateModel(
            name='ProblemPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Прогнозируемый балл')),
                ('difficulty_level', models.CharField(blank=True, choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=20, verbose_name='Уровень сложности')),
                ('problem_areas', models.JSONField(default=list, verbose_name='Проблемные области')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уверенность (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='main.submission', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Прогноз проблем',
                'verbose_name_plural': 'Прогнозы проблем',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main.specialty', verbose_name='Специальность'),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема')),
                ('understanding_level', models.IntegerField(choices=[(1, 'Плохо'), (2, 'Удовлетворительно'), (3, 'Хорошо'), (4, 'Отлично')], verbose_name='Уровень понимания')),
                ('issues', models.JSONField(default=list, verbose_name='Проблемы')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='main.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Прогресс студента',
                'verbose_name_plural': 'Прогресс студентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код предмета')),
                ('name_kk', models.CharField(max_length=200, verbose_name='Название (каз)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('credits', models.IntegerField(default=3, verbose_name='Кредиты')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main.specialty')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.subject', verbose_name='Предмет'),
        ),
    ]
