# Generated by Django 5.2.7 on 2025-12-02 15:54

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_uniquest_academic_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='main_attend_date_afda52_idx',
            old_name='main_attend_date_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='main_course_code_b948e5_idx',
            old_name='main_course_code_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='main_studen_email_dad883_idx',
            old_name='main_studen_email_idx',
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='schedule_entries',
                to='main.group',
                verbose_name='Учебная группа'
            ),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='vector_embedding',
            field=models.JSONField(
                blank=True,
                null=True,
                help_text='Embedding для семантического поиска',
                verbose_name='Векторное представление',
            ),
        ),
    ]
