# Generated by Django 5.2.7 on 2025-12-02 15:54

import django.db.models.deletion
import main.models
from django.db import migrations, models
from django.db.migrations.operations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_uniquest_academic_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='main_attend_date_afda52_idx',
            old_name='main_attend_date_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='main_course_code_b948e5_idx',
            old_name='main_course_code_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='main_studen_email_dad883_idx',
            old_name='main_studen_email_idx',
        ),
        # Сначала удаляем старое поле vector_embedding (если оно было типа double precision[])
        migrations.RunSQL(
            # Удаляем старое поле, если оно существует
            sql="ALTER TABLE main_lecture DROP COLUMN IF EXISTS vector_embedding;",
            reverse_sql="-- Reverse migration not needed",
        ),
        # Затем добавляем новое поле как JSONField
        migrations.AddField(
            model_name='lecture',
            name='vector_embedding',
            field=models.JSONField(
                blank=True,
                null=True,
                help_text='Embedding для семантического поиска',
                verbose_name='Векторное представление',
            ),
        ),
    ]
