# Generated by Django 5.2.7 on 2025-12-02 15:54

import django.db.models.deletion
import main.models
from django.db import migrations, models
from django.db.migrations.operations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_uniquest_academic_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='main_attend_date_afda52_idx',
            old_name='main_attend_date_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='main_course_code_b948e5_idx',
            old_name='main_course_code_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='main_studen_email_dad883_idx',
            old_name='main_studen_email_idx',
        ),
        # Удаляем старое поле vector_embedding (если оно было типа double precision[])
        # и добавляем новое как JSONField
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    -- Удаляем старое поле, если оно существует
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='main_lecture' AND column_name='vector_embedding'
                    ) THEN
                        ALTER TABLE main_lecture DROP COLUMN vector_embedding;
                    END IF;
                    
                    -- Добавляем новое поле как JSONB, если его еще нет
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='main_lecture' AND column_name='vector_embedding'
                    ) THEN
                        ALTER TABLE main_lecture ADD COLUMN vector_embedding JSONB;
                    END IF;
                END $$;
            """,
            reverse_sql="-- Reverse migration not needed",
        ),
    ]
