# Generated by Django 5.2.7 on 2025-12-03 08:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_scheduleentry_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'Посещаемость', 'verbose_name_plural': 'Посещаемость'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-academic_year', 'semester', 'code'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at'], 'verbose_name': 'Запись на курс', 'verbose_name_plural': 'Записи на курсы'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лекция', 'verbose_name_plural': 'Лекции'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='main_attend_date_afda52_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='main_course_code_b948e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='main_studen_email_dad883_idx',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='date_recorded',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('homework', 'Домашнее задание'), ('project', 'Проект'), ('quiz', 'Контрольная работа'), ('exam', 'Экзамен'), ('lab', 'Лабораторная работа')], default='homework', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.course'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='main.enrollment'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='main.lecture'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=False, verbose_name='Присутствовал'),
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Осенний'), (2, 'Весенний')], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='main.assignment'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='assignment_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название задания'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.course'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='grade',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='main.enrollment'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='letter_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=5),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='content_text',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='content_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='main.course'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='vector_embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='Векторное представление'),
        ),
        migrations.AlterField(
            model_name='problemprediction',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='problemprediction',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=20),
        ),
        migrations.AlterField(
            model_name='problemprediction',
            name='predicted_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='problemprediction',
            name='problem_areas',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='problemprediction',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problemprediction',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='main.submission'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main.group'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='iin',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main.specialty'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='main.submission'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='classroom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='main.course'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='groups',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='schedule_entries', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_group', to='main.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='main.course'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='issues',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='understanding_level',
            field=models.IntegerField(choices=[(1, 'Плохо'), (2, 'Удовлетворительно'), (3, 'Хорошо'), (4, 'Отлично')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'lecture', 'date')},
        ),
    ]
