# Generated by Django 5.2.7 on 2025-12-03 15:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_attendance_options_alter_course_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='group',
        ),
        migrations.CreateModel(
            name='ExamPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Предсказанная оценка')),
                ('success_probability', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Вероятность успеха (%)')),
                ('current_avg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Текущий средний балл')),
                ('attendance_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Посещаемость (%)')),
                ('assignment_completion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Выполнение заданий (%)')),
                ('recommended_study_hours', models.IntegerField(default=20, verbose_name='Рекомендуемые часы подготовки')),
                ('focus_topics', models.JSONField(default=list, verbose_name='Темы для фокуса')),
                ('risk_factors', models.JSONField(default=list, verbose_name='Факторы риска')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уверенность модели (%)')),
                ('exam_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_predictions', to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предсказание экзамена',
                'verbose_name_plural': 'Предсказания экзаменов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalizedStudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200, verbose_name='Название плана')),
                ('target_date', models.DateTimeField(verbose_name='Целевая дата')),
                ('total_hours', models.IntegerField(default=0, verbose_name='Всего часов')),
                ('daily_schedule', models.JSONField(default=list, verbose_name='Ежедневное расписание')),
                ('topics_priority', models.JSONField(default=dict, verbose_name='Приоритеты тем')),
                ('milestones', models.JSONField(default=list, verbose_name='Вехи')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Персонализированный план обучения',
                'verbose_name_plural': 'Персонализированные планы обучения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartLearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style', models.CharField(choices=[('visual', 'Визуальный'), ('auditory', 'Аудиальный'), ('kinesthetic', 'Кинестетический'), ('reading', 'Чтение/Письмо'), ('mixed', 'Смешанный')], default='mixed', max_length=20, verbose_name='Стиль обучения')),
                ('preferred_study_time', models.CharField(choices=[('morning', 'Утро (6-12)'), ('afternoon', 'День (12-18)'), ('evening', 'Вечер (18-24)'), ('night', 'Ночь (0-6)')], default='afternoon', max_length=20, verbose_name='Предпочтительное время обучения')),
                ('avg_focus_duration', models.IntegerField(default=45, verbose_name='Средняя длительность фокуса (мин)')),
                ('optimal_study_sessions', models.IntegerField(default=3, verbose_name='Оптимальное количество сессий в день')),
                ('learning_velocity', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Скорость обучения (множитель)')),
                ('retention_rate', models.DecimalField(decimal_places=2, default=0.7, max_digits=5, verbose_name='Коэффициент запоминания')),
                ('study_patterns', models.JSONField(default=dict, verbose_name='Паттерны обучения')),
                ('weak_topics', models.JSONField(default=list, verbose_name='Слабые темы')),
                ('strong_topics', models.JSONField(default=list, verbose_name='Сильные темы')),
                ('last_analyzed', models.DateTimeField(auto_now=True, verbose_name='Последний анализ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Умный профиль обучения',
                'verbose_name_plural': 'Умные профили обучения',
            },
        ),
    ]
