# Generated by Django 5.2.7 on 2026-04-25 17:28

from django.db import migrations


def _drop_scheduleentry_group_if_exists(apps, schema_editor):
    table_name = 'main_scheduleentry'
    column_name = 'group_id'

    with schema_editor.connection.cursor() as cursor:
        columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if column_name in columns:
        schema_editor.execute(
            f'ALTER TABLE {schema_editor.quote_name(table_name)} '
            f'DROP COLUMN {schema_editor.quote_name(column_name)}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_lecture_lecture_file'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _drop_scheduleentry_group_if_exists,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='scheduleentry',
                    name='group',
                ),
            ],
        ),
    ]
