# Generated by Django 5.2.7 on 2026-04-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_lecture_lecture_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='group',
        ),
    ]
